M48
; DRILL file {KiCad 9.0.9-9.0.9~ubuntu24.04.1} date 2026-08-17T17:57:16+0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-17T17:57:16+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.9-9.0.9~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X-77.74Y-3.82
X-77.477Y-48.271
X-3.82Y-3.82
X-3.815Y-48.271
M30
